name: Generate and Deploy to Github Pages
# touchme
on:
  push:
    branches: [ "master" ]  # Set a branch name to trigger deployment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          export RINGS='["Adopt", "Trial", "Assess", "Hold"]'
          export QUADRANTS='["Techniques", "Platforms", "Tools", "Languages & Frameworks"]'
          npm run build:prod

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.1
            
        # Filter on branch
        #if: github.ref == 'refs/heads/master'
        with:
          folder: dist # The folder the action should deploy.
